name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Full Output - Upper only
      id: full-output-upper-only
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Full Output - Upper only
        setup-command: ''
        command: python exercise7.py
        input: '75'
        expected-output: Generating random MAC address\.\.\.\r?\n([0-9A-F]{2}:){5}[0-9A-F]{2}\r?\n\r?\nGenerating
          random IPv6 address\.\.\.\r?\n([0-9A-F]{4}:){7}[0-9A-F]{4}
        comparison-method: regex
        timeout: 1
        max-score: 50
    - name: First line
      id: first-line
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: First line
        setup-command: ''
        command: python exercise7.py
        input: '80'
        expected-output: 'Generating random MAC address...

          '
        comparison-method: regex
        timeout: 1
        max-score: 1
    - name: Full output
      id: full-output
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Full output
        setup-command: ''
        command: python exercise7.py
        input: '55'
        expected-output: Generating random MAC address\.\.\.\r?\n([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}\r?\n\r?\nGenerating
          random IPv6 address\.\.\.\r?\n([0-9A-Fa-f]{4}:){7}[0-9A-Fa-f]{4}
        comparison-method: regex
        timeout: 1
        max-score: 20
    - name: Check testingExercise7.py file
      id: check-testingexercise7-py-file
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Check testingExercise7.py file
        setup-command: ''
        command: python testingExercise7.py
        timeout: 5
        max-score: 30
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        FULL-OUTPUT-UPPER-ONLY_RESULTS: "${{steps.full-output-upper-only.outputs.result}}"
        FIRST-LINE_RESULTS: "${{steps.first-line.outputs.result}}"
        FULL-OUTPUT_RESULTS: "${{steps.full-output.outputs.result}}"
        CHECK-TESTINGEXERCISE7-PY-FILE_RESULTS: "${{steps.check-testingexercise7-py-file.outputs.result}}"
      with:
        runners: full-output-upper-only,first-line,full-output,check-testingexercise7-py-file
